/*
Swagger Documentation for text_analyzer app

Swagger Documentation for text_analyzer app (тестовое задание для компании \"Инсит\")

API version: 1.0
Contact: f3d0t0tvmax@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package analyzer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InputsText type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputsText{}

// InputsText struct for InputsText
type InputsText struct {
	Data string `json:"data"`
}

type _InputsText InputsText

// NewInputsText instantiates a new InputsText object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputsText(data string) *InputsText {
	this := InputsText{}
	this.Data = data
	return &this
}

// NewInputsTextWithDefaults instantiates a new InputsText object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputsTextWithDefaults() *InputsText {
	this := InputsText{}
	return &this
}

// GetData returns the Data field value
func (o *InputsText) GetData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *InputsText) GetDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *InputsText) SetData(v string) {
	o.Data = v
}

func (o InputsText) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputsText) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *InputsText) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInputsText := _InputsText{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInputsText)

	if err != nil {
		return err
	}

	*o = InputsText(varInputsText)

	return err
}

type NullableInputsText struct {
	value *InputsText
	isSet bool
}

func (v NullableInputsText) Get() *InputsText {
	return v.value
}

func (v *NullableInputsText) Set(val *InputsText) {
	v.value = val
	v.isSet = true
}

func (v NullableInputsText) IsSet() bool {
	return v.isSet
}

func (v *NullableInputsText) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputsText(val *InputsText) *NullableInputsText {
	return &NullableInputsText{value: val, isSet: true}
}

func (v NullableInputsText) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputsText) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


